namespace PortalCV.Application.DTOs.Privada;

public record PersonalesDto(
    int PersonalesId,
    int CurriculumId,
    string? TipoIdentificacion,
    string? NumeroDocumento,
    DateOnly? FechaExpedicion,
    string? LugarExpedicion,
    string? LibretaMilitarNumero,
    string? LibretaMilitarClase,
    string? PasaporteNumero,
    DateOnly? PasaporteVigencia,
    string? VisaNumero,
    DateOnly? VisaVigencia,
    string? VisaClase,
    string PrimerNombre,
    string? SegundoNombre,
    string PrimerApellido,
    string? SegundoApellido,
    DateOnly? FechaNacimiento,
    string? LugarNacimiento,
    string? Genero,
    string? Nacionalidad,
    string? TipoSangre,
    string? EPS,
    string? Pencion,
    string? Cesantias,
    string? Email,
    string? Celular,
    string? TelefonoFijo,
    string? Pais,
    string? Departamento,
    string? Ciudad,
    string? Barrio,
    string? CodigoPostal,
    string? Direccion,
    string? TipoResidencia,
    /// <summary>Calculado: apunta al endpoint de foto binaria si hay una subida, o a la
    /// URL legacy pegada por el usuario si no. Nunca se escribe directo -- ver
    /// PersonalesController: PUT/DELETE .../foto.</summary>
    string? FotoUrl);

public record UpsertPersonalesRequest(
    string? TipoIdentificacion,
    string? NumeroDocumento,
    DateOnly? FechaExpedicion,
    string? LugarExpedicion,
    string? LibretaMilitarNumero,
    string? LibretaMilitarClase,
    string? PasaporteNumero,
    DateOnly? PasaporteVigencia,
    string? VisaNumero,
    DateOnly? VisaVigencia,
    string? VisaClase,
    string PrimerNombre,
    string? SegundoNombre,
    string PrimerApellido,
    string? SegundoApellido,
    DateOnly? FechaNacimiento,
    string? LugarNacimiento,
    string? Genero,
    string? Nacionalidad,
    string? TipoSangre,
    string? EPS,
    string? Pencion,
    string? Cesantias,
    string? Email,
    string? Celular,
    string? TelefonoFijo,
    string? Pais,
    string? Departamento,
    string? Ciudad,
    string? Barrio,
    string? CodigoPostal,
    string? Direccion,
    string? TipoResidencia);

/// <summary>Bytes crudos de una foto de perfil ya subida, listos para devolver con
/// <c>File(Contenido, ContentType)</c>.</summary>
public record ArchivoContenidoDto(byte[] Contenido, string ContentType);

